### ISSUE TITLE
Bug: Confirm OTP does not give any message/error on wrong OTP entered

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#86] opened 2020-11-12 03:58 UTC
Confirm OTP does not give any message/error on wrong OTP entered

**Comment by bevanamit** [comment] 2020-11-12 03:59
There should be a error message and the Confirm OTP button should be disabled

**Comment by kshitijbhardwaj** [comment] 2020-11-17 05:26
This needs to be handled in backend. Assigning to anmol

**Comment by theheapdump** [comment] 2020-11-17 07:02
ok i will take care of this. @bevanamit

**Comment by theheapdump** [comment] 2020-11-18 11:27
Not a bug - Closing this - Reopen if required.

**Comment by theheapdump** [comment] 2020-11-18 11:27
![image](https://user-images.githubusercontent.com/7692754/99524934-2ae3da00-29bf-11eb-80e5-8bce541d57f8.png)

**Comment by theheapdump** [comment] 2020-11-19 08:42
please check this and close if ok

**Comment by bevanamit** [comment] 2020-11-19 14:58
tested
![image](https://user-images.githubusercontent.com/5267251/99682939-ce0f1f00-2aa5-11eb-9416-10939955a875.png)

**Closed as completed** 2020-11-22 11:16 UTC
Labels: tested, completed
