### ISSUE TITLE
Bug: Opening Tradebull shows user logged in even after the laptop/desktop was restarted and the User had not logged out

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#159] opened 2020-12-03 06:15 UTC
Observation
I had accessed the TB and logged in 
The machine was shut down and the next day i opened browser directly opened from bookmark (https://35.187.245.85:8080/#/login?returnUrl=%2F)... i see the below page...and when i try doing some action only then i am redirected to login page

![image](https://user-images.githubusercontent.com/5267251/100971498-0cecac80-355d-11eb-90ee-f8aee54ff070.png)

**Comment by theheapdump** [comment] 2020-12-03 07:07
This is right -> only after a HTTP[s] call is send to backend - a session expired will be received .

Currently this only hit is chart-ink.

In future this will be a license-call or subscruption call or a get-plan call .

**Comment by theheapdump** [comment] 2020-12-03 07:07
This is not a bug .

**Comment by theheapdump** [comment] 2020-12-03 07:08
@bevanamit

**Comment by bevanamit** [comment] 2020-12-03 07:09
Ok

**Comment by theheapdump** [comment] 2020-12-09 17:35
Closing this as not a bug !! if it reoccurs, we can re-open this .
@bevanamit

**Closed as completed by theheapdump** 2020-12-09 17:35 UTC
Labels: bug
