### ISSUE TITLE
Bug: Have Links to Profile page and Broker page for modification as and when required . Duplicate of #130 

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#99] opened 2020-11-17 17:54 UTC
Have Links to Profile page and Broker page for modification as and when required

**Comment by kshitijbhardwaj** [comment] 2020-11-17 18:07
@bevanamit  This will be implemented with profile setting page

**Comment by bevanamit** [comment] 2020-11-17 18:10
Is this committed??

**Comment by bevanamit** [comment] 2020-11-17 18:11
If this is not done yet, please assign once that is implemented

**Comment by kshitijbhardwaj** [comment] 2020-11-17 18:11
No sir wo page bana hi nhi hai abhi will be handled with it.

**Comment by kshitijbhardwaj** [comment] 2020-11-17 18:15
I think we can close this issue for now

**Comment by theheapdump** [comment] 2020-11-18 18:38
@bevanamit  backlog

**Comment by theheapdump** [comment] 2020-11-20 11:21
This is a duplicate of #130 . Closing this as duplicate

**Closed as completed by theheapdump** 2020-11-20 11:21 UTC
Labels: duplicate, kite-web-backlog
