### ISSUE TITLE
Bug: New user login, updating Profile and Clicking on Enter key in keyboard does not save the details

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#211] opened 2020-12-16 18:13 UTC
Register new user
Login, he will see profile page
update FN, LN , gender, dob and click ENTER Key in keyboard.

**Comment by theheapdump** [comment] 2020-12-16 20:15
Looks like duplicate of #117

**Comment by theheapdump** [comment] 2020-12-16 20:15
@bevanamit @kshitijbhardwaj

**Comment by kshitijbhardwaj** [comment] 2020-12-18 08:29
This is not possible as happening in login and register. same thing which i have done in login and register i implemented here also. But since there are other components here like Date picker and all. the dom structure of the form is getting broken. 
So to save this you have to click or tab to the update button and press enter.
Hence closing the issue. Same is the case with #117

**Comment by kshitijbhardwaj** [comment] 2020-12-18 08:29
mentioned above

**Closed as completed** 2020-12-18 08:29 UTC
Labels: bug, release
