### ISSUE TITLE
Bug: Customer Onboarded successfully with Invalid Email using API

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#51] opened 2020-11-05 07:12 UTC
Data 

   email = "test1234testcom"
    password = "123456"
    referralcode = "234567"
    dob = "11-11-2020"
    phonenumber = "9874586958"

Response
b'{"redirectTo":null,"status":"SUCCESS","status_message":"Customer Onboarded successfully","response":{"cusId":"TBPCtest09858
234","sts":"REGISTERED","email":"test1234testcom"}}'

Expected
Invalid Email Id

**Comment by theheapdump** [comment] 2020-11-05 07:20
use the bug projects for defect

**Comment by bevanamit** [comment] 2020-11-05 07:22
Oh wil check where is that

**Comment by bevanamit** [comment] 2020-11-05 07:22
And will move it there

**Comment by theheapdump** [comment] 2020-11-05 07:22
what do you mean invalid email ..... OTP will not be confirmed with an invalid email ?? @bevanamit

**Comment by theheapdump** [comment] 2020-11-05 07:22
it will always stay in REGISTERED state @bevanamit

**Comment by bevanamit** [comment] 2020-11-05 07:24
That is true... Otp will not be confirmed... But the point was it was
giving onboarded without proper error in api response

**Comment by theheapdump** [comment] 2020-11-05 07:25
@kshitijbhardwaj  should handle email validation on UI . right @bevanamit . i will also add a backend check

**Comment by theheapdump** [comment] 2020-11-05 07:25
if that's right assign it to @kshitijbhardwaj

**Comment by bevanamit** [comment] 2020-11-05 08:39
@kshitijbhardwaj please handle this in UI

**Comment by kshitijbhardwaj** [comment] 2020-11-05 09:06
Its already handled in UI issue was coming in api testing

**Comment by theheapdump** [comment] 2020-11-05 09:37
@bevanamit  - ?? api testing issue

**Comment by bevanamit** [comment] 2020-11-05 10:14
@anmoldeep0123 yes...its written in description actually

**Comment by theheapdump** [comment] 2020-11-05 12:51
> @anmoldeep0123 yes...its written in description actually

 issue was coming in api testing from KKS

**Comment by theheapdump** [comment] 2020-11-11 18:55
@bevanamit , please retest this and if fine , we can close this

**Comment by bevanamit** [comment] 2020-11-11 18:57
Have you fixed anything here??

**Comment by theheapdump** [comment] 2020-11-11 19:02
NO  !!

**Comment by theheapdump** [comment] 2020-11-11 19:02
is there any thing to fix here !!

**Comment by bevanamit** [comment] 2020-11-11 19:08
There was.... Will check it out and update accordingly

**Comment by theheapdump** [comment] 2020-11-12 03:36
if the issue is still there - please update . @bevanamit

**Comment by bevanamit** [comment] 2020-11-12 03:53
Issue persists: Invalid email sent via api

INFO     root:test_clientregister.py:38 Test: Registration of new client.
INFO     root:test_clientregister.py:51 {'ref': '234567', 'phnNum': '9874586958', 'email': 'test1234testcom', 'passwd': '123456', 'cnfmPasswd': '123456'}
DEBUG    urllib3.connectionpool:connectionpool.py:939 Starting new HTTPS connection (1): 35.187.245.85:8080
DEBUG    urllib3.connectionpool:connectionpool.py:433 https://35.187.245.85:8080 "POST /tb/ui/v1/users/register HTTP/1.1" 200 None
INFO     root:test_clientregister.py:53 200
INFO     root:test_clientregister.py:54 b'{"redirectTo":null,"status":"SUCCESS","status_message":"Customer Onboarded successfully","response":{"cusId":"TBPCtest09858
234","sts":"REGISTERED","email":"test1234testcom"}}'
PASSED

**Comment by theheapdump** [comment] 2020-11-17 03:09
ok it's via API - so back end validation needs to be there. Fine . will take care of this

**Comment by bevanamit** [comment] 2020-11-17 03:15
Ok

**Comment by theheapdump** [comment] 2020-11-18 11:30
Assigning To @bevanamit  - please test

**Comment by bevanamit** [comment] 2020-11-19 15:13
{"redirectTo":null,"status":"ERROR","status_message":"Invalid Email Address","response":null}

**Closed as completed** 2020-11-19 15:13 UTC
Labels: tested, completed
